version: "3"
services:
  node-app:
    build:
      context: ./node-api
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    networks:
      - app-network

  flask-app:
    build:
      context: ./flask-api
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
      - flask-app
    networks:
      - app-network

networks:
  app-network:
